# Este workflow irá construir e enviar uma aplicação Node.js para o Azure Web App
# quando um commit for enviado para o branch padrão.

# Para instruções de como configurar esse workflow, veja:
# https://docs.microsoft.com/en-us/azure/app-service/quickstart-nodejs?tabs=linux&pivots=development-environment-cli

on:
  push:
    branches: [ "main" ]     # O workflow será executado quando um commit for enviado para o branch 'main'.
  workflow_dispatch:           # Permite disparar o workflow manualmente a partir da interface do GitHub.

env:
  AZURE_WEBAPP_NAME: kai-webapp       # Nome do seu Azure Web App, substitua 'kai-webapp' pelo nome real.
  AZURE_WEBAPP_PACKAGE_PATH: '.'      # Caminho do projeto, '.' indica que o app está na raiz do repositório.
  NODE_VERSION: '20.x'               # Versão do Node.js a ser utilizada para a aplicação.

permissions:
  contents: read      # Permissão padrão para ler o conteúdo do repositório.

jobs:
  build:
    runs-on: ubuntu-latest  # Ambiente para rodar o job, aqui está configurado para Ubuntu.
    steps:
    - name: Checkout do código
      uses: actions/checkout@v4   # Este passo faz o checkout do repositório.

    - name: Configurar Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}  # Configura a versão do Node.js como especificado na variável de ambiente.
        cache: 'npm'                         # Configura o cache para módulos npm, acelerando builds futuros.

    - name: Instalar dependências, construir e testar
      run: |
        npm install                    # Instala as dependências do projeto.
        npm run build --if-present      # Executa a construção do projeto, caso exista um script 'build' no package.json.
        npm run test --if-present       # Executa os testes, caso exista um script 'test' no package.json.

    - name: Subir o artefato para o job de deploy
      uses: actions/upload-artifact@v4
      with:
        name: node-app                    # Nome do artefato que será usado no job de deploy.
        path: .                            # Caminho dos arquivos do projeto.

  deploy:
    permissions:
      contents: none   # Não são necessárias permissões para este job, apenas para o deploy.
    runs-on: ubuntu-latest  # Ambiente para o job de deploy, também Ubuntu.
    needs: build    # O job de deploy só será executado após o sucesso do job de build.
    environment:
      name: 'Production'  # Nome do ambiente para o deploy (você pode usar 'Development' ou 'Production').
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}  # URL do aplicativo após o deploy.

    steps:
    - name: Baixar artefato do job de build
      uses: actions/download-artifact@v4
      with:
        name: node-app  # Baixa o artefato que foi gerado no job de build.

    - name: Deploy para o Azure WebApp
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}              # Nome do seu Azure Web App, substituído por 'kai-webapp'.
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}  # Perfil de publicação do Azure, armazenado como segredo.
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}      # Caminho para os arquivos da aplicação (geralmente a raiz).
